### ISSUE TITLE
Need RTLD_GLOBAL for linux?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [davidjamesca/ctypesgen#3]
```
I notice that for Darwin, libraryloader.py automatically adds RTLD_GLOBAL
to the dlopen flags.

On linux, I need RTLD_GLOBAL too though.  For example, this works for me:

import ctypes
ctypes.CDLL('/lib64/libtermcap.so.2', mode=ctypes.RTLD_GLOBAL |
ctypes.RTLD_NOW)
ctypes.CDLL('/usr/lib64/libreadline.so')

But this doesn't:

import ctypes

ctypes.CDLL('/lib64/libtermcap.so.2')
ctypes.CDLL('/usr/lib64/libreadline.so')

$ python t.py
Traceback (most recent call last):
  File "t.py", line 4, in ?
    ctypes.CDLL('/usr/lib64/libreadline.so')
  File "/usr/lib64/python2.4/site-packages/ctypes/__init__.py", line 340,
in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libreadline.so: undefined symbol: BC

The same thing happens if I call dlopen directly from C, so it's not a
ctypes issue.
```

Original issue reported on code.google.com by `michael....@gmail.com` on 17 Dec 2008 at 7:36

**Comment by Alan-R** [comment]
Old. Original requestor information lost. Closing.

**Comment by mara004** [comment]
I had an undefined symbol issue similar to the OP, though on FreeBSD.

As far as I can tell, this happens when a shared library implicitly depends on other libs, which don't show up in the library's `ldd` output but are nevertheless needed at runtime.

That's when the `.so` is part of a larger work that depends on those libraries directly so under normal circumstances they are already loaded (like when the program is run).
However, when you want to interface with such a library directly using ctypes, the implicit dependency libraries must be manually preloaded with `RTLD_GLOBAL` before the bindings module is imported.

ctypesgen can't really do anything about that; you need to manually track down those implicit dependencies and open them with `RTLD_GLOBAL` beforehand.

Alternatively, as a user, you could `export LD_PRELOAD=...`  to the colon-separated library paths (not dirs) in question.

----

For reference, this is the workaround code from pypdfium2 where we pre-load libraries with `RTLD_GLOBAL` (on FreeBSD):
https://github.com/pypdfium2-team/pypdfium2/blob/cb286a85cbe18c347328c4640f8b1fd848835e6d/src/pypdfium2_raw/__init__.py#L4-L19
This fixes the undefined symbol error seen in https://github.com/pypdfium2-team/pypdfium2/pull/411#issuecomment-4106775596

**Comment by mara004** [comment]
The only case where I see an issue is when you want to actually bind against the implicit dependency library/libraries as well.
For that case, an option could be added to let the caller set the desired CDLL opening mode. That shouldn't be hard to add, I think.

**Comment by mara004** [comment]
(I came to this old thread from https://github.com/python/cpython/issues/64475#issuecomment-1093642468, which links here, through a redirect from ctypesgen's former google code home)
