### ISSUE TITLE
Ignore load_library failure at runtime, sometimes?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [davidjamesca/ctypesgen#4]
```
I have a library that I'm running on darwin and on linux.

On linux, the linker needs -ltermcap -lreadline, but on darwin it only
needs -lreadline, and there is no termcap.dylib.

I was hoping I could create a single mylib.py that could load readline. 
However, if I use -ltermcap -lreadline to build mylib.py, the module won't
load in python, because there's no -ltermcap, so load_library will raise an
ImportError.  However, on darwin this doesn't matter, because readline
doesn't need termcap, and I'm not referencing any symbols defined in
libtermcap.

In load_library, I tried commenting out the raise ImportError, and
returning None instead, but I'm not sure if that will cause other problems.

```

Original issue reported on code.google.com by `michael....@gmail.com` on 17 Dec 2008 at 11:16

**Comment by Alan-R** [comment]
Old. Original requestor information lost. Closing. Please reopen if you need this capability. In addition, this sounds like it would be an issue in C or any language...

**Comment by dmvinson** [comment]
I would love the ability to do this if it was possible/easy to implement. I have code that imports a ctypesgen-generated module that can't run on mac because the shared library I'm using is not available on mac. This unfortunately breaks functionality that does not actually depend on the shared library, but just has the ctypesgen generated code in the dependency change. This would be great as a CLI flag.
